name: Deploy Site to Production
on:
  push:
    branches:
      - main
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Build Site
        run: |
          python builder.py
      - name: Checkout GH Pages
        uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages
      - name: Copy Built Site
        run: |
          rsync -av --delete build/ gh-pages/
      - name: Push Site to Production
        run: |
          git -C gh-pages/ config user.name "Builder"
          git -C gh-pages/ config user.email "c3ruleant@gmail.com"
          git -C gh-pages/ add .
          git -C gh-pages/ commit -am "Deploy ${{ github.sha }} to prod"
          git -C gh-pages/ push origin gh-pages
          
