name: Deploy Site to Production
on:
  push:
    branches:
      - main
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: source
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r source/requirements.txt
      - name: Build Site
        run: |
          python source/builder.py
      - name: Checkout GH Pages
        uses: actions/checkout@v2
        with:
          path: deploy
          ref: gh-pages

      - name: Copy Built Site
        run: |
          rsync -av --delete source/build/ deploy/
      - name: Push Site to Production
        run: |
          git -C deploy/ config user.name "Builder"
          git -C deploy/ config user.email "c3ruleant@gmail.com"
          git -C deploy/ add .
          git -C deploy/ commit -am "Deploy ${{ github.sha }} to prod"
          git -C deploy/ push origin gh-pages
